runner_variant:
  - gnu_omp
  - gnu_mpi_omp
  - intel

is_intel:
  - false
  - false
  - true

with_mpi:
  - false
  - true
  - false

c_stdlib_version:    # [linux]
  - "2.17"           # [linux]
  - "2.17"           # [linux]
  - "2.28"           # [linux]

zip_keys:
  - - runner_variant
    - is_intel
    - with_mpi
    - c_stdlib_version  # [linux]
